# Generated by Django 4.2.3 on 2023-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('course', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
